### PR TITLE
Fix inconsistent CoM position

### LINKED ISSUE #312: Inconsistent CoM from restart file
The CoM position is not reproducible from the restart file since the OpenMP loop used `schedule( runtime )` instead of `schedule( static )` to reduce the weighted value.

### PR DESCRIPTION
**Pull request by ChunYen-Chen**
Resolve #312. Thanks @hsinhaoHHuang for the useful discussion.

### CODE REVIEW

File: src/Auxiliary/Aux_FindWeightedAverageCenter.cpp [hunk 1]
```diff
@@ -209,7 +209,7 @@ void Aux_FindWeightedAverageCenter( double WeightedAverageCenter[], const double
                                   MinDens_No, MinPres_No, MinTemp_No, MinEntr_No, DE_Consistency_No );
             }
 
-#           pragma omp parallel for reduction ( +:W_ThisRank, WX_ThisRank, WY_ThisRank, WZ_ThisRank ) schedule( runtime )
+#           pragma omp parallel for reduction ( +:W_ThisRank, WX_ThisRank, WY_ThisRank, WZ_ThisRank ) schedule( static )
```
Comment (hyschive) [inline src/Auxiliary/Aux_FindWeightedAverageCenter.cpp:212]: Add the comment "//       use the "static" schedule for reproducibility"

Comment (ChunYen-Chen) [reply src/Auxiliary/Aux_FindWeightedAverageCenter.cpp:213]: Done!

**Review by hyschive — APPROVED** [review]
