### PR TITLE
[Bugfix] Fix MPI deadlock

### LINKED ISSUE #465: MPI Barrier Synchronization Mismatch in InvokeSolver()
### 🔎 What happened?

When
(1) the Makefile option `TIMING_SOLVER` is on (`--timing_solver=true` in `generate_make.sh`),
(2) the runtime option `OPT__TIMING_BARRIER` in `Input__Parameter` is on, and
(3) the number of patches in different ranks is not balanced,
the program may hang.

The problem might come from the loop in `InvokeSolver(), src/Main/InvokeSolver.cpp`
```c++
   for (Disp=NPG_Max; Disp<NTotal; Disp+=NPG_Max)
   {

      ArrayID      = 1 - ArrayID;
      NPG[ArrayID] = ( NPG_Max < NTotal-Disp ) ? NPG_Max : NTotal-Disp;


//-------------------------------------------------------------------------------------------------------------
      TIMING_SYNC(   Preparation_Step( TSolver, lv, TimeNew, TimeOld, NPG[ArrayID], PID0_List+Disp, ArrayID, GlobalTree ),
                     Timer_Pre[lv][TSolver]  );
//-------------------------------------------------------------------------------------------------------------


//-------------------------------------------------------------------------------------------------------------
#     ifdef GPU
      CUAPI_Synchronize();
#     endif
//-------------------------------------------------------------------------------------------------------------


//-------------------------------------------------------------------------------------------------------------
      TIMING_SYNC(   Solver( TSolver, lv, TimeNew, TimeOld, NPG[ArrayID], ArrayID, dt, Poi_Coeff ),
                     Timer_Sol[lv][TSolver]  );
//-------------------------------------------------------------------------------------------------------------


//-------------------------------------------------------------------------------------------------------------
      TIMING_SYNC(   Closing_Step( TSolver, lv, SaveSg_Flu, SaveSg_Mag, SaveSg_Pot,
                     NPG[1-ArrayID], PID0_List+Disp-NPG_Max, 1-ArrayID, dt ),
                     Timer_Clo[lv][TSolver]  );
//-------------------------------------------------------------------------------------------------------------

   } // for (int Disp=NPG_Max; Disp<NTotal; Disp+=NPG_Max)
```
, where `TIMING_SYNC` is defined in `include/Timer.h`:
```c++
// macro for timing solvers
#if ( defined TIMING_SOLVER  &&  defined TIMING )

#  ifdef GPU
#     define GPU_SYNC()  CUAPI_Synchronize()
#  else
#     define GPU_SYNC()
#  endif

#  define TIMING_SYNC( call, timer )                              \
   {                                                              \
      if ( OPT__TIMING_BARRIER ) MPI_Barrier( MPI_COMM_WORLD );   \
      timer->Start();                                             \
      call;                                                       \
      GPU_SYNC();                                                 \
      if ( OPT__TIMING_BARRIER ) MPI_Barrier( MPI_COMM_WORLD );   \
      timer->Stop();                                              \
   }

#else

#  define TIMING_SYNC( call, timer )   call

#endif
```
If `NTotal/NPG_Max` differs in different MPI ranks, the number of iterations of the for loop is different. Then, some MPI ranks exit earlier, while others are still in the loop. The MPI ranks cannot synchronize through `MPI_Barrier()`, and it becomes a deadlock.

### 📃 Steps to reproduce

Run the test problem `Hydro/Plummer` with the following modifications from the default setup:
- In `generate_make.sh`
   - `--timing_solver=true`
- In `Input__Parameter`,
   - `NX0_TOT_X/Y/Z       = 128`
   - `OMP_NTHREAD         = 1`
   - `FLU_GPU_NPGROUP     = 1`
   - `GPU_NSTREAM         = 1`
   - `OPT__TIMING_BARRIER = 1`
- In `submit_eureka.job`
   - Use 1 node with 16 MPI ranks.
   - `mpirun -map-by ppr:16:socket:pe=1 --report-bindings ./gamer 1>>log 2>&1`

Then the simulation will hang in the first step
   - It hangs after `Lv  1: Par_PassParticle2Son (massive)    ... done`, before `Lv  2: Flu_AdvanceDt, counter =        0 ...`.
   - Some ranks have `80` Lv2 patches and others have `72` Lv2 patches.

As a test, if we delete the two lines in `TIMING_SYNC(), include/Timer.h`
```
      if ( OPT__TIMING_BARRIER ) MPI_Barrier( MPI_COMM_WORLD );   \
```
, then the simulation will not hang.

### ⌚ Commit hash

3f3471fdfc1dbafaa43189e01381a36052e8e6d6

### 🔧 Configuration command

python3 configure.py --mpi=true --hdf5=true --fftw=FFTW3 --gpu=true --model=HYDRO --particle=true --gravity=true --timing_solver=true

### 🔨 Source files modified

None.

### 💻 Operating system

linux (x86)

### 💾 Machine configuration file

`eureka_intel.config`

### 🔖 Related topics

- [ ] Hydro
- [ ] MHD
- [ ] FDM
- [ ] AMR
- [ ] Gravity
- [ ] Particle
- [x] Parallelization
- [ ] GPU
- [ ] Memory
- [ ] YT
- [ ] Tool
- [ ] Docs
- [ ] Other

### 💬 Additional information

_No response_

### PR DESCRIPTION
**Pull request by hyschive**
Resolve the issue #465 and replace the pull request #489

### CODE REVIEW

File: src/Main/InvokeSolver.cpp [hunk 1]
```diff
@@ -219,11 +222,16 @@ void InvokeSolver( const Solver_t TSolver, const int lv, const double TimeNew, c
...
+// use NTotal_Max rather than NTotal in the loop termination criterion below so that all ranks execute the same number of iterations
+// --> avoid potential MPI deadlocks caused by TIMING_SYNC + OPT__TIMING_BARRIER when different ranks have different numbers of patches
+   for (Disp=NPG_Max; Disp<NTotal_Max; Disp+=NPG_Max)
    {
 
-      ArrayID      = 1 - ArrayID;
-      NPG[ArrayID] = ( NPG_Max < NTotal-Disp ) ? NPG_Max : NTotal-Disp;
+      ArrayID = 1 - ArrayID;
+
+      const int NPG_Remained = NTotal - Disp;
```
Comment (hsinhaoHHuang) [inline src/Main/InvokeSolver.cpp]: [Minor]
```suggestion
      const int NPG_Remained = NTotal - Disp;
```

File: src/Main/InvokeSolver.cpp [hunk 2]
```diff
@@ -219,11 +222,16 @@ void InvokeSolver( const Solver_t TSolver, const int lv, const double TimeNew, c
 //-------------------------------------------------------------------------------------------------------------
 
 
-   for (Disp=NPG_Max; Disp<NTotal; Disp+=NPG_Max)
+// use NTotal_Max rather than NTotal in the loop termination criterion below so that all ranks execute the same number of iterations
+// --> avoid potential MPI deadlocks caused by TIMING_SYNC + OPT__TIMING_BARRIER when different ranks have different numbers of patches
+   for (Disp=NPG_Max; Disp<NTotal_Max; Disp+=NPG_Max)
```
Comment (hsinhaoHHuang) [inline src/Main/InvokeSolver.cpp:227]: [Minor]
At Line. 262,
```
    } // for (Disp=NPG_Max; Disp<NTotal_Max; Disp+=NPG_Max)
```

File: src/Main/InvokeSolver.cpp [hunk 3]
```diff
@@ -306,6 +314,10 @@ void Preparation_Step( const Solver_t TSolver, const int lv, const double TimeNe
                        const int *PID0_List, const int ArrayID, LB_GlobalTree* GlobalTree )
 {
 
+// skip if there are no target patches
+   if ( NPG == 0 )   return;
```
Comment (hsinhaoHHuang) [inline src/Main/InvokeSolver.cpp]: The situation seems more complicated than I said in issue #465.
There are also `TIMING_SYNC` inside `Preparation_Step()` for
- `Poi_Prepare_Rho()`
- `Poi_Prepare_Pot()`
- `Gra_Prepare_Corner()`
- `Gra_Prepare_Flu()`
- `Gra_Prepare_USG()`

If some ranks with NPG == 0 return here, there is still a deadlock.
Maybe we can move `if ( NPG == 0 )   return` one more layer inside those functions.


This issue can be reproduced by adding `POT_GPU_NPGROUP   1` to the case in issue #465.
(I will also update the issue description there.)
The simulation will hang during the initialization:
```
Calculating gravitational potential ...
   Lv  0 ... done
   Lv  1 ... done
   Lv  2 ...
```

**Review by hsinhaoHHuang — CHANGES_REQUESTED** [review]

File: src/Main/InvokeSolver.cpp (hunk 3 above)
Comment (hyschive) [reply src/Main/InvokeSolver.cpp]: @hsinhaoHHuang Nice catch! For simplicity, I've decided to remove this `if (NPG == 0 )` check, since all functions should behave correctly when `NPG == 0`.

**Review by hsinhaoHHuang — APPROVED** [review]
Thank you for the update.
I've completed the review and done some tests. I think this PR is good.
